e---
title: "Unit 8-9 | EDA1"
author: "Lani Lewis"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# LIBRARIES ####
library(maps) # lat and long
library(usmap)
library(caret) # confusion Matrix
library(e1071) # navebayes
#library(tm) #text mining library provides the stopwords() function
library(tidyr)
#library(plyr)
#library(jsonlite)
library(dplyr)
library(tidyverse)
library(stringr) # string manipulation
#library(mvtnorm)
library(ggplot2)
library(ggthemes) # Plot Themes
```


```{r}
# IMPORT DATASETS ####
# Import Beers data set
beers <- read.csv(choose.files(),header = T)
```
```{r}
# Import Breweries data set
breweries <- read.csv(choose.files(),header = T)
```
```{r}
# Import Breweries data set
state_abb_list <- read.csv(choose.files(),header = T)
```

```{r}
# UNDERSTAND DATASETS ####
# What kind of data am I looking at
str(beers)

str(breweries)

str(state_abb_list)
```

```{r}
# REVIEW MISSING VALUES ####
# beers dataset has missing values in IBU & ABV column
view(beers)

## SFAE BEER DATASET CHECKPOINT ####
safe_beers = beers

# There is missing values in some of the rows not all. 
```

```{r}
## Look at only NA Values in beers data set ####
beers_na = beers

# create a logical vector indicating which rows have missing values
na_rows <- apply(is.na(beers_na), 1, any)

beers_na <- beers_na[na_rows, ]

str(beers)
str(beers_na)
```

```{r}
#### Check and make sure I only see na in ABV and IBU columns ####
which(is.na(beers_na), arr.ind = TRUE)
```

```{r}
#### Count how many objects are NA in the ABV column ####
str(which(is.na(beers_na$ABV), arr.ind = TRUE))
# 62 rows
```

```{r}
#### Count how many objects are NA in the IBU column ####
str(which(is.na(beers_na$IBU), arr.ind = TRUE))
# 1005 rows
```

```{r}
#### Understand which rows are missing both ABV and IBU ####
str(which(is.na(beers_na$IBU) & is.na(beers_na$ABV), arr.ind = TRUE))
which(is.na(beers_na$IBU) & is.na(beers_na$ABV), arr.ind = TRUE)

# 62 matches so for every ABV NA there will also be an NA IBU
# Check this theory
beers_na[112, ] # Double Play Pilsner | 1541
beers_na[117, ] # N Street Drive-In 50th Anniversary IPA |  1025
beers_na[123, ] # Professor Black | 2490
beers_na[124, ] # Little Boss | 2489
beers_na[125, ] # Van Dayum! | 2488
```

```{r}
# EXPORT NA FIELDS TO CSV ####
write.csv(beers_na, "Missing_Data.csv", row.names = T)
```

```{r}
# RENAME NA FIELDS ####
beers$ABV <- ifelse(is.na(beers$ABV),"Missing_ABV_Data",beers$ABV)
beers$IBU <- ifelse(is.na(beers$IBU),"Missing_IBU_Data",beers$IBU)


str(which(is.na(beers$IBU) & is.na(beers$ABV), arr.ind = TRUE))

view(beers)
```

```{r}
# MERGE DATA ####
# Rename Column Names for Consistency and Merge Process
colnames(beers)[5] <- c("Brew_ID")
colnames(beers)[1] <- c("Beer_Name")
colnames(breweries)[2] <- c("Brewery")

colnames(safe_beers)[5] <- c("Brew_ID")
colnames(safe_beers)[1] <- c("Beer_Name")


# Merge Data
beer_ds <- merge(beers,breweries, by = "Brew_ID")

all_beer_ds <- merge(safe_beers,breweries, by = "Brew_ID")
str(beer_ds)
str(all_beer_ds)
```

```{r}
# How many breweries are present in each state? ####
state_cnt <- beer_ds %>% count(State, sort = T)
colnames(state_cnt)[2] <- "Number_of_States"
state_cnt <- arrange(state_cnt, desc(Number_of_States))
str(state_cnt)
```

```{r}
# PLOT1 Facet Wrap| How many breweries are present in each state? ####
state_cnt %>% arrange(state_cnt, desc(Number_of_States)) %>%
  ggplot(aes(x = Number_of_States, fill = State)) +
  geom_histogram() +
  xlab("Number of Breweries by States") +
  ylab("") +
  facet_wrap(Number_of_States ~ State) +
  scale_y_discrete() +
  theme(legend.position = "none")
  
```

```{r}
# PLOT2 Bar Chart| How many breweries are present in each state? ####
head(state_cnt, 10) %>% 
  ggplot(aes(x = Number_of_States, y = State, fill = State)) +
  geom_bar(stat = "identity") 
```

```{r}
# REMOVE STRING VALUES FROM NUMERIC COLUMN SO MATHMATICAL FORUMALS WILL WORK ####
beers_ds <- beer_ds

beers_ds$State = as.factor(beers_ds$State)
beers_ds$IBU = as.numeric(beers_ds$IBU)
beers_ds$ABV = as.numeric(beers_ds$ABV)

beers_ds <- beers_ds %>%
  filter(!is.character(IBU))

beers_ds <- beers_ds %>%
  filter(!is.character(ABV))

beers_ds = drop_na(beers_ds)

view(beers_ds)
```

```{r}
# HANDLING MISSING VALUES WITH CUMPUTED VALUES ####
safe_beers$Style = as.factor(safe_beers$Style)

style_ABV_cnt <- aggregate(ABV ~ Style, safe_beers, median)
style_IBU_cnt <- aggregate(IBU ~ Style, safe_beers, median)

test <- ifelse(is.na(safe_beers$ABV) & safe_beers$Style == style_ABV_cnt$Style , style_ABV_cnt, safe_beers$ABV)
safe_beers$IBU <- ifelse(is.na(safe_beers$IBU), style_IBU_cnt, safe_beers$IBU)

?filter
str(safe_beers)
```

```{r}
# DATAFRAME FOR MEDIAN AND MEAN VALUES ####
# WILL BE USED FOR PLOTTING
plot_ds <- as.data.frame(matrix(nrow = 50, ncol = 0))

plot_ds
```

```{r}
# Compute the median alcohol content and international bitterness unit for each state. ####
## IBU Median by State ####
plot_ds <- beers_ds %>% group_by(State) %>%
  summarise(median = median(IBU))

plot_ds <- arrange(plot_ds, desc(median))

colnames(plot_ds)[2] <- c("IBU_Median")

plot_ds
```

```{r}
## ABV median by State ####
ABV_Median <- beers_ds %>% group_by(State) %>%
  summarise(median = median(ABV))

ABV_Median <- arrange(ABV_Median, desc(median))

ABV_Median

# Merge data with Plot data
plot_ds <- merge(plot_ds, ABV_Median, by = "State")

colnames(plot_ds)[3] <- c("ABV_Median")

plot_ds
```

```{r}
## IBU Mean by State ####
IBU_Mean <- beers_ds %>% group_by(State) %>%
  summarise(mean = mean(IBU))

IBU_Mean <- arrange(IBU_Mean, desc(mean))

IBU_Mean

# Merge data with Plot data
plot_ds <- merge(plot_ds, IBU_Mean, by = "State")

colnames(plot_ds)[4] <- c("IBU_Mean")

plot_ds
```

```{r}
## ABV Mean by State ####
ABV_Mean <- beers_ds %>% group_by(State) %>%
  summarise(mean = mean(ABV))

ABV_Mean <- arrange(ABV_Mean, desc(mean))

ABV_Mean

# Merge data with Plot data
plot_ds <- merge(plot_ds, ABV_Mean, by = "State")

colnames(plot_ds)[5] <- c("ABV_Mean")

plot_ds
```

```{r}
# MERGE MEDIAN DATASET WITH STATE ABBREVIATIONS ####
plt_ds = plot_ds

# Change from factor to character
plt_ds$State <- as.character(plt_ds$State)

# Remove spaces in state field
plt_ds$State <- gsub("\\s", "", plt_ds$State)

# Change column names
colnames(state_abb_list)[1] <- c("Full_State")
colnames(state_abb_list)[3] <- c("State")

# Left Merge the data
plt_ds <- merge(plt_ds, state_abb_list, by = "State", all.x = T )

str(plt_ds)

```

```{r}
# MERGE STATE LAT AND LONG ####

# Has Lat and long cordinates
US_Map <- map_data("world") %>% filter(region=="USA")

# rename column for merge
colnames(US_Map)[6] <- c("Full_State")


str(US_Map)
str(plt_ds)

view(US_Map)

# Left Merge 
plt_ds = view(merge(plt_ds, US_Map, by = "Full_State", all.x = T))

view(plt_ds)
```

```{r}
# MAP PLOT IBU MEDIAN AND MEAN ####
# US MAP 
plot_usmap(regions = "states") + 
  labs(title = "U.S. States",
       subtitle = "This is a blank map of the United States.") + 
  theme(panel.background=element_blank())

## MAINE MAP PLOT ####
plot_usmap(include = c("ME")) +
  labs(title = "MAINE") +
  theme(panel.background = element_rect(color = "blue"))

## COLORADO MAP PLOT ####
plot_usmap(include = c("CO")) +
  labs(title = "COLORADO") +
  theme(panel.background = element_rect(color = "blue"))

## NEW ENGLAND PLOT ####
plot_usmap(include = c("CT", "ME", "MA", "NH", "VT")) +
  labs(title = "New England Region") +
  theme(panel.background = element_rect(color = "blue"))

# MAP PLOT NEEDS LAT AND LONG FOR STATE ABBREVIATION TO WORK
plt_ds %>% ggplot() +
  geom_polygon(aes(x = long, y = lat, group = group)) +
  geom_point(aes(x = IBU_Mean, y = IBU_Median, fill = State))
  

```

```{r}
# PLOT IBU Median by States ####
plot_ds %>% arrange(IBU_Median, desc(State)) %>%
  ggplot(aes(x = IBU_Median, fill = State)) +
  geom_histogram() +
  xlab("IBU Median by States") +
  ylab("") +
  facet_wrap(IBU_Median ~ State) +
  scale_y_discrete() +
  theme(legend.position = "none")

```

```{r}
# FIX ROUNDING ####
plot_ds$IBU_Mean <- round(plot_ds$IBU_Mean, digits = 3)

# PLOT IBU Mean by States ####
plot_ds %>% arrange(IBU_Mean, desc(State)) %>%
  ggplot(aes(x = IBU_Mean, fill = State)) +
  geom_histogram() +
  xlab("IBU Mean by States") +
  ylab("") +
  facet_wrap(IBU_Mean ~ State) +
  scale_y_discrete() +
  theme(legend.position = "none")

```

```{r}
# FIX ROUNDING ####
plot_ds$ABV_Median <- round(plot_ds$ABV_Median, digits = 3)

# PLOT ABV Median by States ####
plot_ds %>% arrange(ABV_Median, desc(State)) %>%
  ggplot(aes(x = ABV_Median, fill = State)) +
  geom_histogram() +
  xlab("ABV Median by States") +
  ylab("") +
  facet_wrap(ABV_Median ~ State) +
  scale_y_discrete() +
  theme(legend.position = "none")

```

```{r}
# FIX ROUNDING ####
plot_ds$ABV_Mean <- round(plot_ds$ABV_Mean, digits = 3)

# PLOT ABV Mean by States ####
plot_ds %>% arrange(ABV_Mean, desc(State)) %>%
  ggplot(aes(x = ABV_Mean, fill = State)) +
  geom_histogram() +
  xlab("ABV Mean by States") +
  ylab("") +
  facet_wrap(ABV_Mean ~ State) +
  scale_y_discrete() +
  theme(legend.position = "none")

```

```{r}
str()